---
- name: installing Vagrant dmg package
  mac_pkg:
    archive_type: dmg
    archive_path: Vagrant.pkg
    pkg_name: com.vagrant.vagrant
    pkg_version: "{{ vagrant_version }}"
    url: "{{ vagrant_download_url }}/{{ vagrant_version }}/{{vagrant_binary_name }}"
  become: yes
